### ISSUE TITLE
Package RamiGO is not on Bioconductor

### ISSUE THREAD

**Issue by llrs** [mariavica/mircomb#22]
Since version 3.9 the RamiGO package is not available to install. This makes this package not installable.  Maybe it could be updated (I think that the only affected function is `plotGO`).

Thanks

**Comment by mariavica** [comment]
Thanks for noticing! I've updated the package without the `plotGo` function (I didn't use this one that much, if you need to use this function let me know and we can try to find an alternative).
I hope miRComb it's working now, I've still problems to install the package in my current computer but I'm not sure if it is because of its configuration (I'm checking it, something about `Rmpfr` dependences).
Let me know if you have further problems. Best regards,
M

**Comment by llrs** [comment]
I could install it without problems now. Thanks!
